enum UsageType {
	LinearControl = 'LC',
	OnOffControl = 'OOC',
	MomentaryControl = 'MC',
	OneShotControl = 'OSC',
	Selector = 'Sel',
	StaticValue = 'SV',
	StaticFlag = 'SF',
	DynamicValue = 'DV',
	DynamicFlag = 'DF',
	NamedArray = 'Nary',
	CollectionApplication = 'CA',
	CollectionLogical = 'CL',
	CollectionPhysical = 'CP',
	CollectionUsageSwitch = 'US',
	CollectionUsageModifier = 'UM',
	Reserved = '',
}

export interface KeyboardUsage {
	name?: string;
	hidName: string;
	usageType: UsageType;
	keyCode: number;
}

export const keyboardKeypadPage: Record<string, KeyboardUsage> = {
	0x00: { keyCode: 0x00, hidName: 'Reserved (no event indicated)', name: 'Reserved', usageType: UsageType.Selector },
	0x01: { keyCode: 0x01, hidName: 'Keyboard ErrorRollOver', name: 'errorRollOver', usageType: UsageType.Selector },
	0x02: { keyCode: 0x02, hidName: 'Keyboard POSTFail', name: 'POSTFail', usageType: UsageType.Selector },
	0x03: { keyCode: 0x03, hidName: 'Keyboard ErrorUndefined', name: 'ErrorUndefined', usageType: UsageType.Selector },
	0x04: { keyCode: 0x04, hidName: 'Keyboard a', name: 'a', usageType: UsageType.Selector },
	0x05: { keyCode: 0x05, hidName: 'Keyboard b', name: 'b', usageType: UsageType.Selector },
	0x06: { keyCode: 0x06, hidName: 'Keyboard c', name: 'c', usageType: UsageType.Selector },
	0x07: { keyCode: 0x07, hidName: 'Keyboard d', name: 'd', usageType: UsageType.Selector },
	0x08: { keyCode: 0x08, hidName: 'Keyboard e', name: 'e', usageType: UsageType.Selector },
	0x09: { keyCode: 0x09, hidName: 'Keyboard f', name: 'f', usageType: UsageType.Selector },
	0x0a: { keyCode: 0x0a, hidName: 'Keyboard g', name: 'g', usageType: UsageType.Selector },
	0x0b: { keyCode: 0x0b, hidName: 'Keyboard h', name: 'h', usageType: UsageType.Selector },
	0x0c: { keyCode: 0x0c, hidName: 'Keyboard i', name: 'i', usageType: UsageType.Selector },
	0x0d: { keyCode: 0x0d, hidName: 'Keyboard j', name: 'j', usageType: UsageType.Selector },
	0x0e: { keyCode: 0x0e, hidName: 'Keyboard k', name: 'k', usageType: UsageType.Selector },
	0x0f: { keyCode: 0x0f, hidName: 'Keyboard l', name: 'l', usageType: UsageType.Selector },
	0x10: { keyCode: 0x10, hidName: 'Keyboard m', name: 'm', usageType: UsageType.Selector },
	0x11: { keyCode: 0x11, hidName: 'Keyboard n', name: 'n', usageType: UsageType.Selector },
	0x12: { keyCode: 0x12, hidName: 'Keyboard o', name: 'o', usageType: UsageType.Selector },
	0x13: { keyCode: 0x13, hidName: 'Keyboard p', name: 'p', usageType: UsageType.Selector },
	0x14: { keyCode: 0x14, hidName: 'Keyboard q', name: 'q', usageType: UsageType.Selector },
	0x15: { keyCode: 0x15, hidName: 'Keyboard r', name: 'r', usageType: UsageType.Selector },
	0x16: { keyCode: 0x16, hidName: 'Keyboard s', name: 's', usageType: UsageType.Selector },
	0x17: { keyCode: 0x17, hidName: 'Keyboard t', name: 't', usageType: UsageType.Selector },
	0x18: { keyCode: 0x18, hidName: 'Keyboard u', name: 'u', usageType: UsageType.Selector },
	0x19: { keyCode: 0x19, hidName: 'Keyboard v', name: 'v', usageType: UsageType.Selector },
	0x1a: { keyCode: 0x1a, hidName: 'Keyboard w', name: 'w', usageType: UsageType.Selector },
	0x1b: { keyCode: 0x1b, hidName: 'Keyboard x', name: 'x', usageType: UsageType.Selector },
	0x1c: { keyCode: 0x1c, hidName: 'Keyboard y', name: 'y', usageType: UsageType.Selector },
	0x1d: { keyCode: 0x1d, hidName: 'Keyboard z', name: 'z', usageType: UsageType.Selector },
	0x1e: { keyCode: 0x1e, hidName: 'Keyboard 1', name: '1', usageType: UsageType.Selector },
	0x1f: { keyCode: 0x1f, hidName: 'Keyboard 2', name: '2', usageType: UsageType.Selector },
	0x20: { keyCode: 0x20, hidName: 'Keyboard 3', name: '3', usageType: UsageType.Selector },
	0x21: { keyCode: 0x21, hidName: 'Keyboard 4', name: '4', usageType: UsageType.Selector },
	0x22: { keyCode: 0x22, hidName: 'Keyboard 5', name: '5', usageType: UsageType.Selector },
	0x23: { keyCode: 0x23, hidName: 'Keyboard 6', name: '6', usageType: UsageType.Selector },
	0x24: { keyCode: 0x24, hidName: 'Keyboard 7', name: '7', usageType: UsageType.Selector },
	0x25: { keyCode: 0x25, hidName: 'Keyboard 8', name: '8', usageType: UsageType.Selector },
	0x26: { keyCode: 0x26, hidName: 'Keyboard 9', name: '9', usageType: UsageType.Selector },
	0x27: { keyCode: 0x27, hidName: 'Keyboard 0', name: '0', usageType: UsageType.Selector },
	0x28: { keyCode: 0x28, hidName: 'Keyboard Return', name: 'Return', usageType: UsageType.Selector },
	0x29: { keyCode: 0x29, hidName: 'Keyboard ESCAPE', name: 'ESCAPE', usageType: UsageType.Selector },
	0x2a: { keyCode: 0x2a, hidName: 'Keyboard DELETE', name: 'DELETE', usageType: UsageType.Selector },
	0x2b: { keyCode: 0x2b, hidName: 'Keyboard Tab', name: 'Tab', usageType: UsageType.Selector },
	0x2c: { keyCode: 0x2c, hidName: 'Keyboard Spacebar', name: 'Spacebar', usageType: UsageType.Selector },
	0x2d: { keyCode: 0x2d, hidName: 'Keyboard -', name: '-', usageType: UsageType.Selector },
	0x2e: { keyCode: 0x2e, hidName: 'Keyboard =', name: '=', usageType: UsageType.Selector },
	0x2f: { keyCode: 0x2f, hidName: 'Keyboard [', name: '[', usageType: UsageType.Selector },
	0x30: { keyCode: 0x30, hidName: 'Keyboard ]', name: ']', usageType: UsageType.Selector },
	0x31: { keyCode: 0x31, hidName: 'Keyboard \\', name: '\\', usageType: UsageType.Selector },
	0x32: { keyCode: 0x32, hidName: 'Keyboard Non-US #', name: 'Non-US #', usageType: UsageType.Selector },
	0x33: { keyCode: 0x33, hidName: 'Keyboard ;', name: ';', usageType: UsageType.Selector },
	0x34: { keyCode: 0x34, hidName: 'Keyboard ‘', name: '‘', usageType: UsageType.Selector },
	0x35: { keyCode: 0x35, hidName: 'Keyboard Grave Accent', name: 'Grave Accent', usageType: UsageType.Selector },
	0x36: { keyCode: 0x36, hidName: 'Keyboard ,', name: ',', usageType: UsageType.Selector },
	0x37: { keyCode: 0x37, hidName: 'Keyboard .', name: '.', usageType: UsageType.Selector },
	0x38: { keyCode: 0x38, hidName: 'Keyboard /', name: '/', usageType: UsageType.Selector },
	0x39: { keyCode: 0x39, hidName: 'Keyboard Caps Lock', name: 'caps lock', usageType: UsageType.Selector },
	0x3a: { keyCode: 0x3a, hidName: 'Keyboard F1', name: 'F1', usageType: UsageType.Selector },
	0x3b: { keyCode: 0x3b, hidName: 'Keyboard F2', name: 'F2', usageType: UsageType.Selector },
	0x3c: { keyCode: 0x3c, hidName: 'Keyboard F3', name: 'F3', usageType: UsageType.Selector },
	0x3d: { keyCode: 0x3d, hidName: 'Keyboard F4', name: 'F4', usageType: UsageType.Selector },
	0x3e: { keyCode: 0x3e, hidName: 'Keyboard F5', name: 'F5', usageType: UsageType.Selector },
	0x3f: { keyCode: 0x3f, hidName: 'Keyboard F6', name: 'F6', usageType: UsageType.Selector },
	0x40: { keyCode: 0x40, hidName: 'Keyboard F7', name: 'F7', usageType: UsageType.Selector },
	0x41: { keyCode: 0x41, hidName: 'Keyboard F8', name: 'F8', usageType: UsageType.Selector },
	0x42: { keyCode: 0x42, hidName: 'Keyboard F9', name: 'F9', usageType: UsageType.Selector },
	0x43: { keyCode: 0x43, hidName: 'Keyboard F10', name: 'F10', usageType: UsageType.Selector },
	0x44: { keyCode: 0x44, hidName: 'Keyboard F11', name: 'F11', usageType: UsageType.Selector },
	0x45: { keyCode: 0x45, hidName: 'Keyboard F12', name: 'F12', usageType: UsageType.Selector },
	0x46: { keyCode: 0x46, hidName: 'Keyboard PrintScreen', name: 'PrintScreen', usageType: UsageType.Selector },
	0x47: { keyCode: 0x47, hidName: 'Keyboard Scroll Lock', name: 'Scroll Lock', usageType: UsageType.Selector },
	0x48: { keyCode: 0x48, hidName: 'Keyboard Pause', name: 'Pause', usageType: UsageType.Selector },
	0x49: { keyCode: 0x49, hidName: 'Keyboard Insert', name: 'Insert', usageType: UsageType.Selector },
	0x4a: { keyCode: 0x4a, hidName: 'Keyboard Home', name: 'Home', usageType: UsageType.Selector },
	0x4b: { keyCode: 0x4b, hidName: 'Keyboard PageUp', name: 'PageUp', usageType: UsageType.Selector },
	0x4c: { keyCode: 0x4c, hidName: 'Keyboard Delete Forward', name: 'Delete Forward', usageType: UsageType.Selector },
	0x4d: { keyCode: 0x4d, hidName: 'Keyboard End', name: 'End', usageType: UsageType.Selector },
	0x4e: { keyCode: 0x4e, hidName: 'Keyboard PageDown', name: 'PageDown', usageType: UsageType.Selector },
	0x4f: { keyCode: 0x4f, hidName: 'Keyboard RightArrow', name: 'RightArrow', usageType: UsageType.Selector },
	0x50: { keyCode: 0x50, hidName: 'Keyboard LeftArrow', name: 'LeftArrow', usageType: UsageType.Selector },
	0x51: { keyCode: 0x51, hidName: 'Keyboard DownArrow', name: 'DownArrow', usageType: UsageType.Selector },
	0x52: { keyCode: 0x52, hidName: 'Keyboard UpArrow', name: 'UpArrow', usageType: UsageType.Selector },
	0x53: { keyCode: 0x53, hidName: 'Keypad Num Lock', name: 'Keypad Num Lock', usageType: UsageType.Selector },
	0x54: { keyCode: 0x54, hidName: 'Keypad /', name: 'Keypad /', usageType: UsageType.Selector },
	0x55: { keyCode: 0x55, hidName: 'Keypad *', name: 'Keypad *', usageType: UsageType.Selector },
	0x56: { keyCode: 0x56, hidName: 'Keypad -', name: 'Keypad -', usageType: UsageType.Selector },
	0x57: { keyCode: 0x57, hidName: 'Keypad +', name: 'Keypad +', usageType: UsageType.Selector },
	0x58: { keyCode: 0x58, hidName: 'Keypad ENTER', name: 'Keypad ENTER', usageType: UsageType.Selector },
	0x59: { keyCode: 0x59, hidName: 'Keypad 1', name: 'Keypad 1', usageType: UsageType.Selector },
	0x5a: { keyCode: 0x5a, hidName: 'Keypad 2', name: 'Keypad 2', usageType: UsageType.Selector },
	0x5b: { keyCode: 0x5b, hidName: 'Keypad 3', name: 'Keypad 3', usageType: UsageType.Selector },
	0x5c: { keyCode: 0x5c, hidName: 'Keypad 4', name: 'Keypad 4', usageType: UsageType.Selector },
	0x5d: { keyCode: 0x5d, hidName: 'Keypad 5', name: 'Keypad 5', usageType: UsageType.Selector },
	0x5e: { keyCode: 0x5e, hidName: 'Keypad 6', name: 'Keypad 6', usageType: UsageType.Selector },
	0x5f: { keyCode: 0x5f, hidName: 'Keypad 7', name: 'Keypad 7', usageType: UsageType.Selector },
	0x60: { keyCode: 0x60, hidName: 'Keypad 8', name: 'Keypad 8', usageType: UsageType.Selector },
	0x61: { keyCode: 0x61, hidName: 'Keypad 9', name: 'Keypad 9', usageType: UsageType.Selector },
	0x62: { keyCode: 0x62, hidName: 'Keypad 0', name: 'Keypad 0', usageType: UsageType.Selector },
	0x63: { keyCode: 0x63, hidName: 'Keypad .', name: 'Keypad .', usageType: UsageType.Selector },
	0x64: { keyCode: 0x64, hidName: 'Keyboard Non \\', name: 'Non \\', usageType: UsageType.Selector },
	0x65: { keyCode: 0x65, hidName: 'Keyboard Application', name: 'Application', usageType: UsageType.Selector },
	0x66: { keyCode: 0x66, hidName: 'Keyboard Power', name: 'Power', usageType: UsageType.Selector },
	0x67: { keyCode: 0x67, hidName: 'Keypad =', name: 'Keypad =', usageType: UsageType.Selector },
	0x68: { keyCode: 0x68, hidName: 'Keyboard F13', name: 'F13', usageType: UsageType.Selector },
	0x69: { keyCode: 0x69, hidName: 'Keyboard F14', name: 'F14', usageType: UsageType.Selector },
	0x6a: { keyCode: 0x6a, hidName: 'Keyboard F15', name: 'F15', usageType: UsageType.Selector },
	0x6b: { keyCode: 0x6b, hidName: 'Keyboard F16', name: 'F16', usageType: UsageType.Selector },
	0x6c: { keyCode: 0x6c, hidName: 'Keyboard F17', name: 'F17', usageType: UsageType.Selector },
	0x6d: { keyCode: 0x6d, hidName: 'Keyboard F18', name: 'F18', usageType: UsageType.Selector },
	0x6e: { keyCode: 0x6e, hidName: 'Keyboard F19', name: 'F19', usageType: UsageType.Selector },
	0x6f: { keyCode: 0x6f, hidName: 'Keyboard F20', name: 'F20', usageType: UsageType.Selector },
	0x70: { keyCode: 0x70, hidName: 'Keyboard F21', name: 'F21', usageType: UsageType.Selector },
	0x71: { keyCode: 0x71, hidName: 'Keyboard F22', name: 'F22', usageType: UsageType.Selector },
	0x72: { keyCode: 0x72, hidName: 'Keyboard F23', name: 'F23', usageType: UsageType.Selector },
	0x73: { keyCode: 0x73, hidName: 'Keyboard F24', name: 'F24', usageType: UsageType.Selector },
	0x74: { keyCode: 0x74, hidName: 'Keyboard Execute', name: 'Execute', usageType: UsageType.Selector },
	0x75: { keyCode: 0x75, hidName: 'Keyboard Help', name: 'Help', usageType: UsageType.Selector },
	0x76: { keyCode: 0x76, hidName: 'Keyboard Menu', name: 'Menu', usageType: UsageType.Selector },
	0x77: { keyCode: 0x77, hidName: 'Keyboard Select', name: 'Select', usageType: UsageType.Selector },
	0x78: { keyCode: 0x78, hidName: 'Keyboard Stop', name: 'Stop', usageType: UsageType.Selector },
	0x79: { keyCode: 0x79, hidName: 'Keyboard Again', name: 'Again', usageType: UsageType.Selector },
	0x7a: { keyCode: 0x7a, hidName: 'Keyboard Undo', name: 'Undo', usageType: UsageType.Selector },
	0x7b: { keyCode: 0x7b, hidName: 'Keyboard Cut', name: 'Cut', usageType: UsageType.Selector },
	0x7c: { keyCode: 0x7c, hidName: 'Keyboard Copy', name: 'Copy', usageType: UsageType.Selector },
	0x7d: { keyCode: 0x7d, hidName: 'Keyboard Paste', name: 'Paste', usageType: UsageType.Selector },
	0x7e: { keyCode: 0x7e, hidName: 'Keyboard Find', name: 'Find', usageType: UsageType.Selector },
	0x7f: { keyCode: 0x7f, hidName: 'Keyboard Mute', name: 'Mute', usageType: UsageType.Selector },
	0x80: { keyCode: 0x80, hidName: 'Keyboard Volume Up', name: 'Volume Up', usageType: UsageType.Selector },
	0x81: { keyCode: 0x81, hidName: 'Keyboard Volume Down', name: 'Volume Down', usageType: UsageType.Selector },
	0x82: {
		keyCode: 0x82,
		hidName: 'Keyboard Locking Caps Lock',
		name: 'Locking Caps Lock',
		usageType: UsageType.Selector,
	},
	0x83: {
		keyCode: 0x83,
		hidName: 'Keyboard Locking Num Lock',
		name: 'Locking Num Lock',
		usageType: UsageType.Selector,
	},
	0x84: {
		keyCode: 0x84,
		hidName: 'Keyboard Locking Scroll Lock',
		name: 'Locking Scroll Lock',
		usageType: UsageType.Selector,
	},
	0x85: { keyCode: 0x85, hidName: 'Keypad Comma13', name: 'Keypad Comma13', usageType: UsageType.Selector },
	0x86: { keyCode: 0x86, hidName: 'Keypad Equal Sign14', name: 'Keypad Equal Sign14', usageType: UsageType.Selector },
	0x87: { keyCode: 0x87, hidName: 'Keyboard International1', name: 'International1', usageType: UsageType.Selector },
	0x88: { keyCode: 0x88, hidName: 'Keyboard International2', name: 'International2', usageType: UsageType.Selector },
	0x89: { keyCode: 0x89, hidName: 'Keyboard International3', name: 'International3', usageType: UsageType.Selector },
	0x8a: { keyCode: 0x8a, hidName: 'Keyboard International4', name: 'International4', usageType: UsageType.Selector },
	0x8b: { keyCode: 0x8b, hidName: 'Keyboard International5', name: 'International5', usageType: UsageType.Selector },
	0x8c: { keyCode: 0x8c, hidName: 'Keyboard International6', name: 'International6', usageType: UsageType.Selector },
	0x8d: { keyCode: 0x8d, hidName: 'Keyboard International7', name: 'International7', usageType: UsageType.Selector },
	0x8e: { keyCode: 0x8e, hidName: 'Keyboard International8', name: 'International8', usageType: UsageType.Selector },
	0x8f: { keyCode: 0x8f, hidName: 'Keyboard International9', name: 'International9', usageType: UsageType.Selector },
	0x90: { keyCode: 0x90, hidName: 'Keyboard LANG1', name: 'LANG1', usageType: UsageType.Selector },
	0x91: { keyCode: 0x91, hidName: 'Keyboard LANG2', name: 'LANG2', usageType: UsageType.Selector },
	0x92: { keyCode: 0x92, hidName: 'Keyboard LANG3', name: 'LANG3', usageType: UsageType.Selector },
	0x93: { keyCode: 0x93, hidName: 'Keyboard LANG4', name: 'LANG4', usageType: UsageType.Selector },
	0x94: { keyCode: 0x94, hidName: 'Keyboard LANG5', name: 'LANG5', usageType: UsageType.Selector },
	0x95: { keyCode: 0x95, hidName: 'Keyboard LANG6', name: 'LANG6', usageType: UsageType.Selector },
	0x96: { keyCode: 0x96, hidName: 'Keyboard LANG7', name: 'LANG7', usageType: UsageType.Selector },
	0x97: { keyCode: 0x97, hidName: 'Keyboard LANG8', name: 'LANG8', usageType: UsageType.Selector },
	0x98: { keyCode: 0x98, hidName: 'Keyboard LANG9', name: 'LANG9', usageType: UsageType.Selector },
	0x99: {
		keyCode: 0x99,
		hidName: 'Keyboard Alternate Erase',
		name: 'Alternate Erase',
		usageType: UsageType.Selector,
	},
	0x9a: {
		keyCode: 0x9a,
		hidName: 'Keyboard SysReq/Attention',
		name: 'SysReq/Attention',
		usageType: UsageType.Selector,
	},
	0x9b: { keyCode: 0x9b, hidName: 'Keyboard Cancel', name: 'Cancel', usageType: UsageType.Selector },
	0x9c: { keyCode: 0x9c, hidName: 'Keyboard Clear', name: 'Clear', usageType: UsageType.Selector },
	0x9d: { keyCode: 0x9d, hidName: 'Keyboard Prior', name: 'Prior', usageType: UsageType.Selector },
	0x9e: { keyCode: 0x9e, hidName: 'Keyboard Return', name: 'Return', usageType: UsageType.Selector },
	0x9f: { keyCode: 0x9f, hidName: 'Keyboard Separator', name: 'Separator', usageType: UsageType.Selector },
	0xa0: { keyCode: 0xa0, hidName: 'Keyboard Out', name: 'Out', usageType: UsageType.Selector },
	0xa1: { keyCode: 0xa1, hidName: 'Keyboard Oper', name: 'Oper', usageType: UsageType.Selector },
	0xa2: { keyCode: 0xa2, hidName: 'Keyboard Clear/Again', name: 'Clear/Again', usageType: UsageType.Selector },
	0xa3: { keyCode: 0xa3, hidName: 'Keyboard CrSel/Props', name: 'CrSel/Props', usageType: UsageType.Selector },
	0xa4: { keyCode: 0xa4, hidName: 'Keyboard ExSel', name: 'ExSel', usageType: UsageType.Selector },
	0xa5: { keyCode: 0xa5, hidName: 'Reserved', name: 'Reserved', usageType: UsageType.Reserved },
	0xa6: { keyCode: 0xa6, hidName: 'Reserved', name: 'Reserved', usageType: UsageType.Reserved },
	0xa7: { keyCode: 0xa7, hidName: 'Reserved', name: 'Reserved', usageType: UsageType.Reserved },
	0xa8: { keyCode: 0xa8, hidName: 'Reserved', name: 'Reserved', usageType: UsageType.Reserved },
	0xa9: { keyCode: 0xa9, hidName: 'Reserved', name: 'Reserved', usageType: UsageType.Reserved },
	0xaa: { keyCode: 0xaa, hidName: 'Reserved', name: 'Reserved', usageType: UsageType.Reserved },
	0xab: { keyCode: 0xab, hidName: 'Reserved', name: 'Reserved', usageType: UsageType.Reserved },
	0xac: { keyCode: 0xac, hidName: 'Reserved', name: 'Reserved', usageType: UsageType.Reserved },
	0xae: { keyCode: 0xae, hidName: 'Reserved', name: 'Reserved', usageType: UsageType.Reserved },
	0xaf: { keyCode: 0xaf, hidName: 'Reserved', name: 'Reserved', usageType: UsageType.Reserved },
	0xb0: { keyCode: 0xb0, hidName: 'Keypad 00', name: 'Keypad 00', usageType: UsageType.Selector },
	0xb1: { keyCode: 0xb1, hidName: 'Keypad 000', name: 'Keypad 000', usageType: UsageType.Selector },
	0xb2: { keyCode: 0xb2, hidName: 'Thousands Separator', name: 'Thousands Separator', usageType: UsageType.Selector },
	0xb3: { keyCode: 0xb3, hidName: 'Decimal Separator', name: 'Decimal Separator', usageType: UsageType.Selector },
	0xb4: { keyCode: 0xb4, hidName: 'Currency Unit', name: 'Currency Unit', usageType: UsageType.Selector },
	0xb5: { keyCode: 0xb5, hidName: 'Currency Sub', name: 'Currency Sub', usageType: UsageType.Selector },
	0xb6: { keyCode: 0xb6, hidName: 'Keypad (', name: 'Keypad (', usageType: UsageType.Selector },
	0xb7: { keyCode: 0xb7, hidName: 'Keypad )', name: 'Keypad )', usageType: UsageType.Selector },
	0xb8: { keyCode: 0xb8, hidName: 'Keypad {', name: 'Keypad {', usageType: UsageType.Selector },
	0xb9: { keyCode: 0xb9, hidName: 'Keypad }', name: 'Keypad }', usageType: UsageType.Selector },
	0xba: { keyCode: 0xba, hidName: 'Keypad Tab', name: 'Keypad Tab', usageType: UsageType.Selector },
	0xbb: { keyCode: 0xbb, hidName: 'Keypad Backspace', name: 'Keypad Backspace', usageType: UsageType.Selector },
	0xbc: { keyCode: 0xbc, hidName: 'Keypad A', name: 'Keypad A', usageType: UsageType.Selector },
	0xbd: { keyCode: 0xbd, hidName: 'Keypad B', name: 'Keypad B', usageType: UsageType.Selector },
	0xbe: { keyCode: 0xbe, hidName: 'Keypad C', name: 'Keypad C', usageType: UsageType.Selector },
	0xbf: { keyCode: 0xbf, hidName: 'Keypad D', name: 'Keypad D', usageType: UsageType.Selector },
	0xc0: { keyCode: 0xc0, hidName: 'Keypad E', name: 'Keypad E', usageType: UsageType.Selector },
	0xc1: { keyCode: 0xc1, hidName: 'Keypad F', name: 'Keypad F', usageType: UsageType.Selector },
	0xc2: { keyCode: 0xc2, hidName: 'Keypad XOR', name: 'Keypad XOR', usageType: UsageType.Selector },
	0xc3: { keyCode: 0xc3, hidName: 'Keypad ∧', name: 'Keypad ∧', usageType: UsageType.Selector },
	0xc4: { keyCode: 0xc4, hidName: 'Keypad %', name: 'Keypad %', usageType: UsageType.Selector },
	0xc5: { keyCode: 0xc5, hidName: 'Keypad <', name: 'Keypad <', usageType: UsageType.Selector },
	0xc6: { keyCode: 0xc6, hidName: 'Keypad >', name: 'Keypad >', usageType: UsageType.Selector },
	0xc7: { keyCode: 0xc7, hidName: 'Keypad &', name: 'Keypad &', usageType: UsageType.Selector },
	0xc8: { keyCode: 0xc8, hidName: 'Keypad &&', name: 'Keypad &&', usageType: UsageType.Selector },
	0xc9: { keyCode: 0xc9, hidName: 'Keypad |', name: 'Keypad |', usageType: UsageType.Selector },
	0xca: { keyCode: 0xca, hidName: 'Keypad ||', name: 'Keypad ||', usageType: UsageType.Selector },
	0xcb: { keyCode: 0xcb, hidName: 'Keypad :', name: 'Keypad :', usageType: UsageType.Selector },
	0xcc: { keyCode: 0xcc, hidName: 'Keypad #', name: 'Keypad #', usageType: UsageType.Selector },
	0xcd: { keyCode: 0xcd, hidName: 'Keypad Space', name: 'Keypad Space', usageType: UsageType.Selector },
	0xce: { keyCode: 0xce, hidName: 'Keypad @', name: 'Keypad @', usageType: UsageType.Selector },
	0xcf: { keyCode: 0xcf, hidName: 'Keypad !', name: 'Keypad !', usageType: UsageType.Selector },
	0xd0: { keyCode: 0xd0, hidName: 'Keypad Memory Store', name: 'Keypad Memory Store', usageType: UsageType.Selector },
	0xd1: {
		keyCode: 0xd1,
		hidName: 'Keypad Memory Recall',
		name: 'Keypad Memory Recall',
		usageType: UsageType.Selector,
	},
	0xd2: { keyCode: 0xd2, hidName: 'Keypad Memory Clear', name: 'Keypad Memory Clear', usageType: UsageType.Selector },
	0xd3: { keyCode: 0xd3, hidName: 'Keypad Memory Add', name: 'Keypad Memory Add', usageType: UsageType.Selector },
	0xd4: {
		keyCode: 0xd4,
		hidName: 'Keypad Memory Subtract',
		name: 'Keypad Memory Subtract',
		usageType: UsageType.Selector,
	},
	0xd5: {
		keyCode: 0xd5,
		hidName: 'Keypad Memory Multiply',
		name: 'Keypad Memory Multiply',
		usageType: UsageType.Selector,
	},
	0xd6: {
		keyCode: 0xd6,
		hidName: 'Keypad Memory Divide',
		name: 'Keypad Memory Divide',
		usageType: UsageType.Selector,
	},
	0xd7: { keyCode: 0xd7, hidName: 'Keypad +/-', name: 'Keypad +/-', usageType: UsageType.Selector },
	0xd8: { keyCode: 0xd8, hidName: 'Keypad Clear', name: 'Keypad Clear', usageType: UsageType.Selector },
	0xd9: { keyCode: 0xd9, hidName: 'Keypad Clear', name: 'Keypad Clear', usageType: UsageType.Selector },
	0xda: { keyCode: 0xda, hidName: 'Keypad Binary', name: 'Keypad Binary', usageType: UsageType.Selector },
	0xdb: { keyCode: 0xdb, hidName: 'Keypad Octal', name: 'Keypad Octal', usageType: UsageType.Selector },
	0xdc: { keyCode: 0xdc, hidName: 'Keypad Decimal', name: 'Keypad Decimal', usageType: UsageType.Selector },
	0xde: { keyCode: 0xde, hidName: 'Reserved', name: 'Reserved', usageType: UsageType.Reserved },
	0xdf: { keyCode: 0xdf, hidName: 'Reserved', name: 'Reserved', usageType: UsageType.Reserved },
	0xdd: { keyCode: 0xdd, hidName: 'Keypad Hexadecimal', name: 'Keypad Hexadecimal', usageType: UsageType.Selector },
	0xe0: { keyCode: 0xe0, hidName: 'Keyboard LeftControl', name: 'LeftControl', usageType: UsageType.DynamicValue },
	0xe1: { keyCode: 0xe1, hidName: 'Keyboard LeftShift', name: 'LeftShift', usageType: UsageType.DynamicValue },
	0xe2: { keyCode: 0xe2, hidName: 'Keyboard LeftAlt', name: 'LeftAlt', usageType: UsageType.DynamicValue },
	0xe3: { keyCode: 0xe3, hidName: 'Keyboard Left', name: 'Left', usageType: UsageType.DynamicValue },
	0xe4: { keyCode: 0xe4, hidName: 'Keyboard RightControl', name: 'RightControl', usageType: UsageType.DynamicValue },
	0xe5: { keyCode: 0xe5, hidName: 'Keyboard RightShift', name: 'RightShift', usageType: UsageType.DynamicValue },
	0xe6: { keyCode: 0xe6, hidName: 'Keyboard RightAlt', name: 'RightAlt', usageType: UsageType.DynamicValue },
	0xe7: { keyCode: 0xe7, hidName: 'Keyboard Right GUI', name: 'Right GUI', usageType: UsageType.DynamicValue },
};

export enum FirmwareAction {
	// Mouse
	DISABLE_BUTTON = 0x01,
	LEFT_CLICK = 0x02,
	RIGHT_CLICK = 0x03,
	MIDDLE_CLICK = 0x04,
	BACKWARD = 0x05,
	FORWARD = 0x06,
	DOUBLE_CLICK = 0x07,
	FIRE = 0x08,
	SCROLL_UP = 0x09,
	EASY_AIM = 0x10,
	SCROLL_DOWN = 0x0a,
	GLOBAL_DPI_CYCLE = 0x0d,
	GLOBAL_DPI_PLUS = 0x0e,
	GLOBAL_DPI_MINUS = 0x0f,

	// Keyboard
	KEYBOARD = 0x11,
	CUSTOM_MACRO = 0x12,

	// Multimedia
	MEDIA_PLAYER = 0x15,
	PREVIOUS_TRACK = 0x16,
	NEXT_TRACK = 0x17,
	PLAY_PAUSE = 0x18,
	STOP = 0x19,
	MUTE = 0x1a,
	VOL_PLUS = 0x1b,
	VOL_MINUS = 0x1c,

	CALCULATOR = 0x1d,
	EMAIL = 0x1e,
	BROWSER_FORWARD = 0x20,
	BROWSER_BACKWARD = 0x21,
	BROWSER_STOP = 0x22,
	MY_COMPUTER = 0x23,
	BROWSER_REFRESH = 0x24,
	BROWSER_HOME = 0x25,
	BROWSER_SEARCH = 0x26,
	MODE_KEY = 0x3c,
	POLLING_RATE_CYCLE = 0x40,
}

export type MacroTuple = readonly [FirmwareAction, Modifiers, KeyCode | number];

export enum Modifiers {
	None = 0x0,
	CTRL = 0x1,
	SHIFT = 0x2,
	ALT = 0x4,
	WIN = 0x8,
}

// noinspection JSUnusedGlobalSymbols
export enum KeyCode {
	None = 0x00,
	ONLY_USED_BY_EASY_AIM = 0x03, // used by easy-aim

	// Letters
	A = 0x04,
	B = 0x05,
	C = 0x06,
	D = 0x07,
	E = 0x08,
	F = 0x09,
	G = 0x0a,
	H = 0x0b,
	I = 0x0c,
	J = 0x0d,
	K = 0x0e,
	L = 0x0f,
	M = 0x10,
	N = 0x11,
	O = 0x12,
	P = 0x13,
	Q = 0x14,
	R = 0x15,
	S = 0x16,
	T = 0x17,
	U = 0x18,
	V = 0x19,
	W = 0x1a,
	X = 0x1b,
	Y = 0x1c,
	Z = 0x1d,

	// Number row
	DIGIT_1 = 0x1e,
	DIGIT_2 = 0x1f,
	DIGIT_3 = 0x20,
	DIGIT_4 = 0x21,
	DIGIT_5 = 0x22,
	DIGIT_6 = 0x23,
	DIGIT_7 = 0x24,
	DIGIT_8 = 0x25,
	DIGIT_9 = 0x26,
	DIGIT_0 = 0x27,

	// Controls
	ENTER = 0x28,
	ESC = 0x29,
	BACKSPACE = 0x2a,
	TAB = 0x2b,
	LShift = 0xe1,
	RShift = 0xe5,
	LAlt = 0xe2,
	RAlt = 0xe6,
	LCrtl = 0xe0,
	RCrtl = 0xe4,
	LWin = 0xe3,
	RWin = 0xe7,
	SPACE = 0x2c,

	// Symbols
	BRACKET_RIGHT = 0x30,
	BACKSLASH = 0x31,
	NON_US_HASH = 0x32,
	SEMICOLON = 0x33, // Ç in ABNT2
	QUOTE = 0x34,
	BACKQUOTE = 0x35,
	COMMA = 0x36,
	PERIOD = 0x37,
	SLASH = 0x38,
	CAPS_LOCK = 0x39,

	// Function keys
	F1 = 0x3a,
	F2 = 0x3b,
	F3 = 0x3c,
	F4 = 0x3d,
	F5 = 0x3e,
	F6 = 0x3f,
	F7 = 0x40,
	F8 = 0x41,
	F9 = 0x42,
	F10 = 0x43,
	F11 = 0x44,
	F12 = 0x45,

	PRINT_SCREEN = 0x46,
	SCROLL_LOCK = 0x47,
	PAUSE = 0x48,
	INSERT = 0x49,

	// Navigation
	HOME = 0x4a,
	PAGE_UP = 0x4b,
	DELETE = 0x4c,
	END = 0x4d,
	PAGE_DOWN = 0x4e,
	ARROW_RIGHT = 0x4f,
	ARROW_LEFT = 0x50,
	ARROW_DOWN = 0x51,
	ARROW_UP = 0x52,

	// Numpad
	NUM_LOCK = 0x53,
	NUMPAD_DIVIDE = 0x54,
	NUMPAD_MULTIPLY = 0x55,
	NUMPAD_SUBTRACT = 0x56,
	NUMPAD_ADD = 0x57,
	NUMPAD_ENTER = 0x58,
	NUMPAD_1 = 0x59,
	NUMPAD_2 = 0x5a,
	NUMPAD_3 = 0x5b,
	NUMPAD_4 = 0x5c,
	NUMPAD_5 = 0x5d,
	NUMPAD_6 = 0x5e,
	NUMPAD_7 = 0x5f,
	NUMPAD_8 = 0x60,
	NUMPAD_9 = 0x61,
	NUMPAD_0 = 0x62,
	NUMPAD_DECIMAL = 0x63,

	// Intl / extended
	INTL_BACKSLASH = 0x64,
	CONTEXT_MENU = 0x65,
	POWER = 0x66,
	NUMPAD_EQUAL = 0x67,

	F13 = 0x68,
	F14 = 0x69,
	F15 = 0x6a,
	F16 = 0x6b,
	F17 = 0x6c,
	F18 = 0x6d,
	F19 = 0x6e,
	F20 = 0x6f,
	F21 = 0x70,
	F22 = 0x71,
	F23 = 0x72,
	F24 = 0x73,
}

export enum MacroName {
	// Global
	GLOBAL_DISABLE_BUTTON = 'global-disable-button',
	GLOBAL_LEFT_CLICK = 'global-left-click',
	GLOBAL_RIGHT_CLICK = 'global-right-click',
	GLOBAL_MIDDLE = 'global-middle',
	GLOBAL_BACKWARD = 'global-backward',
	GLOBAL_FORWARD = 'global-forward',
	GLOBAL_DOUBLE_CLICK = 'global-double-click',
	GLOBAL_FIRE_BUTTON = 'global-fire-button',
	GLOBAL_SCROLL_UP = 'global-scroll-up',
	GLOBAL_SCROLL_DOWN = 'global-scroll-down',
	GLOBAL_EASY_AIM = 'global-easy-aim',
	GLOBAL_DPI_CYCLE = 'global-dpi-cycle',
	GLOBAL_DPI_PLUS = 'global-dpi-+',
	GLOBAL_DPI_MINUS = 'global-dpi--',

	// Multimedia
	MULTIMEDIA_MEDIA_PLAYER = 'multimedia-media-player',
	MULTIMEDIA_PLAY_PAUSE = 'multimedia-play-pause',
	MULTIMEDIA_STOP_MUSIC = 'multimedia-stop-music',
	MULTIMEDIA_PREVIOUS_TRACK = 'multimedia-previous-track',
	MULTIMEDIA_NEXT_TRACK = 'multimedia-next-track',
	MULTIMEDIA_VOLUME_PLUS = 'multimedia-volume-+',
	MULTIMEDIA_VOLUME_MINUS = 'multimedia-volume--',
	MULTIMEDIA_MUTE = 'multimedia-mute',

	// Browser
	BROWSER_HOME = 'browser-home',
	BROWSER_FAVORITES = 'browser-favorites',
	BROWSER_FORWARD = 'browser-forward',
	BROWSER_BACKWARD = 'browser-backward',
	BROWSER_STOP = 'browser-stop',
	BROWSER_REFRESH = 'browser-refresh',
	BROWSER_SEARCH = 'browser-search',
	BROWSER_EMAIL = 'browser-email',
	BROWSER_CALCULATOR = 'browser-calculator',
	BROWSER_MY_COMPUTER = 'browser-my-computer',

	// Shortcuts
	SHORTCUT_CUT = 'shortcut-cut',
	SHORTCUT_COPY = 'shortcut-copy',
	SHORTCUT_PASTE = 'shortcut-paste',
	SHORTCUT_OPEN = 'shortcut-open',
	SHORTCUT_SAVE = 'shortcut-save',
	SHORTCUT_FIND = 'shortcut-find',
	SHORTCUT_REDO = 'shortcut-redo',
	SHORTCUT_SELECT_ALL = 'shortcut-select-all',
	SHORTCUT_PRINT = 'shortcut-print',
	SHORTCUT_CLOSE_WINDOW = 'shortcut-close-window',
	SHORTCUT_SWAP_WINDOW = 'shortcut-swap-window',
	SHORTCUT_SHOW_DESKTOP = 'shortcut-show-desktop',
	SHORTCUT_RUN_COMMAND = 'shortcut-run-command',
	SHORTCUT_LOCK_PC = 'shortcut-lock-pc',
	SHORTCUT_SCREEN_CAPTURE = 'shortcut-screen-capture',

	CUSTOM_MACRO_LEFT_BUTTON = 'custom-macro-left-button',
	CUSTOM_MACRO_RIGHT_BUTTON = 'custom-macro-right-button',
	CUSTOM_MACRO_MIDDLE_BUTTON = 'custom-macro-middle-button',
	CUSTOM_MACRO_EXTRA_BUTTON_4 = 'custom-macro-extra-button_4',
	CUSTOM_MACRO_EXTRA_BUTTON_5 = 'custom-macro-extra-button_5',
}

export type MacroTemplate = Record<MacroName, MacroTuple>;

export const macroTemplates: MacroTemplate = {
	[MacroName.GLOBAL_DISABLE_BUTTON]: [FirmwareAction.DISABLE_BUTTON, Modifiers.None, KeyCode.None],
	[MacroName.GLOBAL_LEFT_CLICK]: [FirmwareAction.LEFT_CLICK, Modifiers.None, KeyCode.None],
	[MacroName.GLOBAL_RIGHT_CLICK]: [FirmwareAction.RIGHT_CLICK, Modifiers.None, KeyCode.None],
	[MacroName.GLOBAL_MIDDLE]: [FirmwareAction.MIDDLE_CLICK, Modifiers.None, KeyCode.None],
	[MacroName.GLOBAL_BACKWARD]: [FirmwareAction.BACKWARD, Modifiers.None, KeyCode.None],
	[MacroName.GLOBAL_FORWARD]: [FirmwareAction.FORWARD, Modifiers.None, KeyCode.None],
	[MacroName.GLOBAL_DOUBLE_CLICK]: [FirmwareAction.DOUBLE_CLICK, Modifiers.None, KeyCode.None],
	[MacroName.GLOBAL_FIRE_BUTTON]: [FirmwareAction.FIRE, Modifiers.None, KeyCode.None],
	[MacroName.GLOBAL_SCROLL_UP]: [FirmwareAction.SCROLL_UP, Modifiers.None, KeyCode.None],
	[MacroName.GLOBAL_EASY_AIM]: [FirmwareAction.EASY_AIM, Modifiers.None, KeyCode.ONLY_USED_BY_EASY_AIM],
	[MacroName.GLOBAL_SCROLL_DOWN]: [FirmwareAction.SCROLL_DOWN, Modifiers.None, KeyCode.None],
	[MacroName.GLOBAL_DPI_CYCLE]: [FirmwareAction.GLOBAL_DPI_CYCLE, Modifiers.None, KeyCode.None],
	[MacroName.GLOBAL_DPI_PLUS]: [FirmwareAction.GLOBAL_DPI_PLUS, Modifiers.None, KeyCode.None],
	[MacroName.GLOBAL_DPI_MINUS]: [FirmwareAction.GLOBAL_DPI_MINUS, Modifiers.None, KeyCode.None],

	// Multimedia
	[MacroName.MULTIMEDIA_MEDIA_PLAYER]: [FirmwareAction.MEDIA_PLAYER, Modifiers.None, KeyCode.None],
	[MacroName.MULTIMEDIA_PLAY_PAUSE]: [FirmwareAction.PLAY_PAUSE, Modifiers.None, KeyCode.None],
	[MacroName.MULTIMEDIA_STOP_MUSIC]: [FirmwareAction.STOP, Modifiers.None, KeyCode.None],
	[MacroName.MULTIMEDIA_PREVIOUS_TRACK]: [FirmwareAction.PREVIOUS_TRACK, Modifiers.None, KeyCode.None],
	[MacroName.MULTIMEDIA_NEXT_TRACK]: [FirmwareAction.NEXT_TRACK, Modifiers.None, KeyCode.None],
	[MacroName.MULTIMEDIA_VOLUME_PLUS]: [FirmwareAction.VOL_PLUS, Modifiers.None, KeyCode.None],
	[MacroName.MULTIMEDIA_VOLUME_MINUS]: [FirmwareAction.VOL_MINUS, Modifiers.None, KeyCode.None],
	[MacroName.MULTIMEDIA_MUTE]: [FirmwareAction.MUTE, Modifiers.None, KeyCode.None],

	// Browser
	[MacroName.BROWSER_HOME]: [FirmwareAction.BROWSER_HOME, Modifiers.None, KeyCode.None],
	[MacroName.BROWSER_FAVORITES]: [FirmwareAction.KEYBOARD, Modifiers.CTRL | Modifiers.SHIFT, KeyCode.O],
	[MacroName.BROWSER_FORWARD]: [FirmwareAction.BROWSER_FORWARD, Modifiers.None, KeyCode.None],
	[MacroName.BROWSER_BACKWARD]: [FirmwareAction.BROWSER_BACKWARD, Modifiers.None, KeyCode.None],
	[MacroName.BROWSER_STOP]: [FirmwareAction.BROWSER_STOP, Modifiers.None, KeyCode.None],
	[MacroName.BROWSER_REFRESH]: [FirmwareAction.BROWSER_REFRESH, Modifiers.None, KeyCode.None],
	[MacroName.BROWSER_SEARCH]: [FirmwareAction.BROWSER_SEARCH, Modifiers.None, KeyCode.None],
	[MacroName.BROWSER_EMAIL]: [FirmwareAction.EMAIL, Modifiers.None, KeyCode.None],
	[MacroName.BROWSER_CALCULATOR]: [FirmwareAction.CALCULATOR, Modifiers.None, KeyCode.None],
	[MacroName.BROWSER_MY_COMPUTER]: [FirmwareAction.MY_COMPUTER, Modifiers.None, KeyCode.None],

	// Shortcuts
	[MacroName.SHORTCUT_CUT]: [FirmwareAction.KEYBOARD, Modifiers.CTRL, KeyCode.X],
	[MacroName.SHORTCUT_COPY]: [FirmwareAction.KEYBOARD, Modifiers.CTRL, KeyCode.C],
	[MacroName.SHORTCUT_PASTE]: [FirmwareAction.KEYBOARD, Modifiers.CTRL, KeyCode.V],
	[MacroName.SHORTCUT_OPEN]: [FirmwareAction.KEYBOARD, Modifiers.CTRL, KeyCode.O],
	[MacroName.SHORTCUT_SAVE]: [FirmwareAction.KEYBOARD, Modifiers.CTRL, KeyCode.S],
	[MacroName.SHORTCUT_FIND]: [FirmwareAction.KEYBOARD, Modifiers.CTRL, KeyCode.F],
	[MacroName.SHORTCUT_REDO]: [FirmwareAction.KEYBOARD, Modifiers.CTRL, KeyCode.Y],
	[MacroName.SHORTCUT_SELECT_ALL]: [FirmwareAction.KEYBOARD, Modifiers.CTRL, KeyCode.A],
	[MacroName.SHORTCUT_PRINT]: [FirmwareAction.KEYBOARD, Modifiers.CTRL, KeyCode.P],
	[MacroName.SHORTCUT_CLOSE_WINDOW]: [FirmwareAction.KEYBOARD, Modifiers.ALT, KeyCode.F4],
	[MacroName.SHORTCUT_SWAP_WINDOW]: [FirmwareAction.KEYBOARD, Modifiers.ALT, KeyCode.TAB],
	[MacroName.SHORTCUT_SHOW_DESKTOP]: [FirmwareAction.KEYBOARD, Modifiers.WIN, KeyCode.D],
	[MacroName.SHORTCUT_RUN_COMMAND]: [FirmwareAction.KEYBOARD, Modifiers.WIN, KeyCode.R],
	[MacroName.SHORTCUT_LOCK_PC]: [FirmwareAction.KEYBOARD, Modifiers.WIN, KeyCode.L],
	[MacroName.SHORTCUT_SCREEN_CAPTURE]: [FirmwareAction.KEYBOARD, Modifiers.WIN | Modifiers.SHIFT, KeyCode.S],

	[MacroName.CUSTOM_MACRO_LEFT_BUTTON]: [FirmwareAction.CUSTOM_MACRO, Modifiers.None, 0x01],
	[MacroName.CUSTOM_MACRO_RIGHT_BUTTON]: [FirmwareAction.CUSTOM_MACRO, Modifiers.None, 0x02],
	[MacroName.CUSTOM_MACRO_MIDDLE_BUTTON]: [FirmwareAction.CUSTOM_MACRO, Modifiers.None, 0x03],
	[MacroName.CUSTOM_MACRO_EXTRA_BUTTON_4]: [FirmwareAction.CUSTOM_MACRO, Modifiers.None, 0x07],
	[MacroName.CUSTOM_MACRO_EXTRA_BUTTON_5]: [FirmwareAction.CUSTOM_MACRO, Modifiers.None, 0x08],
} satisfies Record<MacroName, MacroTuple>;
